# Dockerfile.build

FROM amazoncorretto:21-alpine as builder

WORKDIR /app

# Gradle 파일 복사
COPY gradlew build.gradle.kts settings.gradle.kts ./
COPY gradle ./gradle
RUN chmod +x ./gradlew

# 의존성 캐싱
RUN ./gradlew dependencies --no-daemon

# 전체 소스 복사
COPY . .

# JAR 빌드
RUN ./gradlew bootJar -x test
