name: dev-deploy

on:
  workflow_dispatch:

jobs:
  deploy-to-docker-dev:
    runs-on: [self-hosted]

    steps:
      - name: Check if JAR exists
        run: ls -lh /Users/jeahoon/IdeaProjects/docker/build/libs/docker-0.0.1-SNAPSHOT.jar

      - name: Build deploy image
        run: |
          docker build -f Dockerfile.deploy -t spring-app .

      - name: Remove existing app container if exists
        run: |
          docker rm -f spring-app || true

      - name: Run Spring app in docker-dev network
        run: |
          docker run -d \
            --name spring-app \
            --network docker-dev_default \
            -p 8080:8080 \
            spring-app

      - name: Remove dangling docker images
        run: docker image prune -f